<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>domain</RootNamespace>
        <AssemblyName>domain</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CredentialManagement" Version="1.0.2" NoWarn="NU1701" />
        <PackageReference Include="System.Security.Permissions" Version="10.0.10" />
    </ItemGroup>

</Project>

