<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>
        <RootNamespace>domain</RootNamespace>
        <AssemblyName>domain</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CredentialManagement" Version="1.0.2" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="IFetchOption.cs" />
        <Compile Include="IOption.cs" />
        <Compile Include="IStoreOption.cs" />
        <Compile Include="Properties\AssemblyInfo.cs"/>
        <Compile Include="CredentialCommand.cs" />
    </ItemGroup>

</Project>

